Issues/23
mamikoprogram/wish-list-v2 pull request #3
Opened 2022-03-24 00:46 UTC by mamikoprogram

『#23　Wish編集』のレビューをお願いします。

2022-03-25 02:00 UTC, tarotyjp requested changes

2022-03-25 02:00 UTC, deve-liba commented on src/learning/edit_done.php
> +<?php
このページはPOSTでの処理を想定していますが、GETアクセス時の処理が書かれていません。
そのため、このページにURL直打ちなのでGETアクセスしたときにはエラーなどが表示されてしまいます。
$_SERVER 変数を利用して、POSTアクセス以外の時にはエラーを出すようにしましょう。

2022-03-25 02:00 UTC, deve-liba commented on src/learning/edit_done.php
> +<?php
更新処理が edit.php と edit_done.phpに分かれています。
似たような処理に、new-wish.phpがありますが、こちらは１つのphpファイルで処理をしています。

ファイルを分けることが駄目というわけじゃないのですが、１つのシステムにおいて異なる方針の処理が実装されているので、実装方針は合わせるようにするとよいです。

ただ、今回は１週目という事もあり、このままでも構いません。

2022-03-25 02:00 UTC, deve-liba commented on src/learning/edit.php
> +        <input type="hidden" name="id" value="<?php
hiddenを利用しているあたり、しっかりと調べてる感じしますね！

2022-03-25 02:00 UTC, tarotyjp commented on src/learning/edit_done.php
> +?>
ファイルの最後のコードがPHPコードの場合、ファイル最後の `?>` (PHP終了タグ）は省略可能です。
付けてもエラーになるわけじゃないのですが、「省略推奨」ではなく、「省略すべき」と覚えておいてください。

省略し忘れることで余計な空白が出力されてしまい、それがもとでエラーとなることもあります。

2022-03-31 13:53 UTC, mamikoprogram commented on src/learning/edit_done.php
> +<?php
遅くなりましたが修正完了しました。
尚、ブランチを間違えてしまい、issues/17 →「＃23 Wish編集（修正作業完了）」の内容でプッシュしております。
ご確認とレビューをよろしくお願いします。

2022-04-04 03:21 UTC, closed without merging